<multiplication_op> ::= "fois" | "multiplié par"

<exclusif_or> ::= "ou exclusif" <|> "xor"

<expr> ::= <term> "plus" <expr>
        |  <term> "moins" <expr>
        | <term>

<term> ::= <factor> <multiplication_op> <term>
        |  <factor> "divisé par" <term>
        |  <factor> "modulo" <term>
        |  <factor>

<factor> ::= "(" <expr> ")"
          |  <const>

<const> ::= integer

<condition> ::= <expression> <operateur_logique> <expression>

<comparison_operator> ::= "est" | "égale" | "différente" | "inférieure" | "supérieure" | "inférieure ou égale" | "supérieure ou égale"

<logical_operator> ::= "et" | "ou" | "et binaire" | "ou binaire"

<bitwise_operator> ::= "décalé binairement à gauche" | "décalé binairement à droite"

<operators> ::= <bitwise_operator> | <logical_operator> | <comparison_operator>

<condition> ::= <name> <operator> <name> | <name> <operator> <paranthesis>

<paranthesis> ::= "(" <operators> ")"

<function_definition> ::= "J’aimerais définir le bloc répondant au nom de" <name> ", de type de retour" <type> ", nécessitant comme entrée :" <spaces> <parameter_list> "; contenant les variables :" <spaces> <variable_list> "; représenté par le code" <code_call> <define_return>"." <spaces> <block> <spaces> "Cordialement," <spaces> <name> <spaces> <name>

<code_call> ::= " "suivant" | "ci-après" | "ci-dessous"

<define_return> ::= ", retournant " <name> | ""

<block> ::= <statement_list> <space> "Merci."

<statement_list> ::= <statement> | <statement> <statement_list>

<statement> ::= <expression_statement> | <return_statement>

<return_statement> ::= "Enfin, renvoie "<name>"." | "Enfin, sors du bloc."

<condition_statement> ::= "Si " <condition> ", exécute le texte :" <space> <block>

<expression_statement> ::= <condition_statement> | <operation_statement>

<operation_statement> ::= <name> <operator> <name> | <name> <operation_statement>

<parameter_list> ::= <parameter> <spaces> | <parameter> <spaces> <parameter_list>

<parameter> ::= <type> <name>

<type> ::= "entier naturel" | "booléen" | "chaîne de caractères"

<name> ::= <identifier>

<variable_list> ::= <variable> <spaces> | <variable> <spaces> <variable_list>

<variable> ::= <name>", de type "<type>", valant "<value>

<space> ::= "\n" | "\t" | "\s"

<spaces> ::= <space> | <space> <spaces>
